
import DAO.ClientesDAO;
import Dados.Clientes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 277700
 */
public class FrmCadClientes extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadClientes
     */
    public FrmCadClientes()
    {
       // this.setExtendedState(MAXIMIZED_BOTH);
        
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void Limpar()
        {
            TextCodigo_Cliente.setText(null);
            TextNome_Cliente.setText(null);
            TextEndereco_Cliente.setText(null);
            TextComplemento_Cliente.setText(null);
            TextEmail_Cliente.setText(null);
            FormTextTelefone_Cliente.setText(null);
            FormTextRg_Cliente.setText(null);
            FormTextCpf_Cliente.setText(null);
        }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        LblCodigo_Cliente = new javax.swing.JLabel();
        TextCodigo_Cliente = new javax.swing.JTextField();
        LblNome_Cliente = new javax.swing.JLabel();
        TextNome_Cliente = new javax.swing.JTextField();
        LblEndereco_Cliente = new javax.swing.JLabel();
        TextEndereco_Cliente = new javax.swing.JTextField();
        LblComplemento_Cliente = new javax.swing.JLabel();
        TextComplemento_Cliente = new javax.swing.JTextField();
        LblEmail_Cliente = new javax.swing.JLabel();
        TextEmail_Cliente = new javax.swing.JTextField();
        LblTelefone_Cliente = new javax.swing.JLabel();
        FormTextTelefone_Cliente = new javax.swing.JFormattedTextField();
        LblRg_Cliente = new javax.swing.JLabel();
        FormTextRg_Cliente = new javax.swing.JFormattedTextField();
        FormTextCpf_Cliente = new javax.swing.JFormattedTextField();
        LblCpf_Cliente = new javax.swing.JLabel();
        ButtonCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastrar = new javax.swing.JTable();
        LblTitulo = new javax.swing.JLabel();
        uttonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SOFTGIA / Cadastro de Clientes");

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        LblCodigo_Cliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblCodigo_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        LblCodigo_Cliente.setText("Código:");

        TextCodigo_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextCodigo_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCodigo_ClienteActionPerformed(evt);
            }
        });

        LblNome_Cliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblNome_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        LblNome_Cliente.setText("Nome:");

        TextNome_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextNome_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNome_ClienteActionPerformed(evt);
            }
        });

        LblEndereco_Cliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblEndereco_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        LblEndereco_Cliente.setText("Endereço:");

        TextEndereco_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblComplemento_Cliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblComplemento_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        LblComplemento_Cliente.setText("Complemento:");

        TextComplemento_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblEmail_Cliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblEmail_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        LblEmail_Cliente.setText("E-mail:");

        TextEmail_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblTelefone_Cliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblTelefone_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        LblTelefone_Cliente.setText("Telefone:");

        FormTextTelefone_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            FormTextTelefone_Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(**) *****-****")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        LblRg_Cliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblRg_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        LblRg_Cliente.setText("RG:");

        FormTextRg_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            FormTextRg_Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("**-**.***.***")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        FormTextCpf_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            FormTextCpf_Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("***.***.***-**")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        LblCpf_Cliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblCpf_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        LblCpf_Cliente.setText("CPF:");

        ButtonCadastrar.setBackground(new java.awt.Color(204, 255, 255));
        ButtonCadastrar.setText("Cadastrar");
        ButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarActionPerformed(evt);
            }
        });

        jTableCadastrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Endereço", "Complemento", "E-mail", "Telefone", "RG", "CPF"
            }
        ));
        jTableCadastrar.setEnabled(false);
        jScrollPane1.setViewportView(jTableCadastrar);

        LblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LblTitulo.setText("Cadastro de Clientes");

        uttonVoltar.setBackground(new java.awt.Color(204, 255, 255));
        uttonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reply.png"))); // NOI18N
        uttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uttonVoltarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo SG.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LblCodigo_Cliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextCodigo_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LblEmail_Cliente)
                                .addGap(18, 18, 18)
                                .addComponent(TextEmail_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(LblTelefone_Cliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FormTextTelefone_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(LblRg_Cliente)
                                .addGap(18, 18, 18)
                                .addComponent(FormTextRg_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblCpf_Cliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FormTextCpf_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(183, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LblNome_Cliente)
                                .addGap(18, 18, 18)
                                .addComponent(TextNome_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(LblEndereco_Cliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TextEndereco_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addComponent(LblComplemento_Cliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextComplemento_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(uttonVoltar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LblTitulo)
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(uttonVoltar)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(LblTitulo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCodigo_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCodigo_Cliente))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNome_Cliente)
                    .addComponent(TextNome_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblRg_Cliente)
                    .addComponent(FormTextRg_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCpf_Cliente)
                    .addComponent(FormTextCpf_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextEmail_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblEmail_Cliente)
                    .addComponent(LblTelefone_Cliente)
                    .addComponent(FormTextTelefone_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblEndereco_Cliente)
                    .addComponent(TextEndereco_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblComplemento_Cliente)
                    .addComponent(TextComplemento_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(ButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextCodigo_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCodigo_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCodigo_ClienteActionPerformed

    private void TextNome_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNome_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNome_ClienteActionPerformed

    private void ButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarActionPerformed
        // TODO add your handling code here:
        String codigo = null, nome = null, endereco = null, complemento = null, email = null, telefone = null, rg = null, cpf = null;
        
        codigo = TextCodigo_Cliente.getText();
        nome = TextNome_Cliente.getText();
        endereco = TextEndereco_Cliente.getText();
        complemento = TextComplemento_Cliente.getText();
        email = TextEmail_Cliente.getText();
        telefone = FormTextTelefone_Cliente.getText();
        rg = FormTextRg_Cliente.getText();
        cpf = FormTextCpf_Cliente.getText();
        
       //if(codigo.equals("")||nome.equals("")||endereco.equals("")||complemento.equals("")||email.equals("")||telefone.equals("")||rg.equals("")||cpf.equals(""))
        //{
          //  jTableCadastrar = null;
            //JOptionPane.showMessageDialog(null, "Confira se todos os dados foram preenchidos corretamente.");
        //}
        //else
        //{
            
        //}     
        
        DefaultTableModel ModelCadastrar = (DefaultTableModel) jTableCadastrar.getModel();
        Object[]informacoes = {codigo, nome, endereco, complemento, email, telefone, rg, cpf};
        ModelCadastrar.addRow(informacoes);
        
        JOptionPane.showMessageDialog(null, "O cliente foi cadastrado com sucesso!");
        
        Limpar();
    }//GEN-LAST:event_ButtonCadastrarActionPerformed

    private void uttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uttonVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_uttonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrar;
    private javax.swing.JFormattedTextField FormTextCpf_Cliente;
    private javax.swing.JFormattedTextField FormTextRg_Cliente;
    private javax.swing.JFormattedTextField FormTextTelefone_Cliente;
    private javax.swing.JLabel LblCodigo_Cliente;
    private javax.swing.JLabel LblComplemento_Cliente;
    private javax.swing.JLabel LblCpf_Cliente;
    private javax.swing.JLabel LblEmail_Cliente;
    private javax.swing.JLabel LblEndereco_Cliente;
    private javax.swing.JLabel LblNome_Cliente;
    private javax.swing.JLabel LblRg_Cliente;
    private javax.swing.JLabel LblTelefone_Cliente;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JTextField TextCodigo_Cliente;
    private javax.swing.JTextField TextComplemento_Cliente;
    private javax.swing.JTextField TextEmail_Cliente;
    private javax.swing.JTextField TextEndereco_Cliente;
    private javax.swing.JTextField TextNome_Cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadastrar;
    private javax.swing.JButton uttonVoltar;
    // End of variables declaration//GEN-END:variables
}
